--- #YAML:1.0
name: Object-Meta-Plugin
version: 0.02_02
license: perl
distribution_type: module
requires:
  Carp: '>= 1.01'
  Scalar::Util: 0
  Tie::RefHash: '>= 1.3'
  autouse: '>= 1.03'
  perl: '>= 5.8.0'
recommends:
  Class::ISA: '>= 0.32'
  Devel::Symdump: '>= 2.03'
build_requires: {}
conflicts: {}
provides:
  Object::Meta::Plugin:
    file: lib/Object/Meta/Plugin.pm
    version: 0.02_02
  Object::Meta::Plugin::ExportList:
    file: lib/Object/Meta/Plugin/ExportList.pm
    version: 0.02
  Object::Meta::Plugin::ExportList::Info:
    file: lib/Object/Meta/Plugin/ExportList.pm
    version: 0.02
  Object::Meta::Plugin::Host:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  Object::Meta::Plugin::Host::Context:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  Object::Meta::Plugin::Host::Context::Offset:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  ? |-
    Object::Meta::Plugin::Host::Context::TiedSelf::ARRAY
:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  ? |-
    Object::Meta::Plugin::Host::Context::TiedSelf::HASH
:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  ? |-
    Object::Meta::Plugin::Host::Context::TiedSelf::SCALAR
:
    file: lib/Object/Meta/Plugin/Host.pm
    version: 0.02
  Object::Meta::Plugin::Useful:
    file: lib/Object/Meta/Plugin/Useful.pm
    version: 0.01
  Object::Meta::Plugin::Useful::Generic:
    file: lib/Object/Meta/Plugin/Useful/Generic.pm
    version: 0.01
  Object::Meta::Plugin::Useful::Greedy:
    file: lib/Object/Meta/Plugin/Useful/Greedy.pm
    version: 0.02
  Object::Meta::Plugin::Useful::Meta:
    file: lib/Object/Meta/Plugin/Useful/Meta.pm
    version: 0.01
generated_by: Module::Build version 0.21
